import {
  Activity,
  AlertTriangle,
  Cloud,
  Cpu,
  Database,
  FileWarning,
  Globe,
  Key,
  Laptop,
  Lock,
  Mail,
  Monitor,
  Network,
  Plug,
  Radar,
  Router as RouterIcon,
  Server,
  Shield,
  ShieldAlert,
  Smartphone,
  UserX,
  Wifi,
  LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  monitor: Monitor,
  laptop: Laptop,
  server: Server,
  router: RouterIcon,
  network: Network,
  shield: Shield,
  lock: Lock,
  wifi: Wifi,
  globe: Globe,
  plug: Plug,
  database: Database,
  mail: Mail,
  cloud: Cloud,
  key: Key,
  smartphone: Smartphone,
  cpu: Cpu,
  radar: Radar,
  "shield-alert": ShieldAlert,
  activity: Activity,
  "user-x": UserX,
  "alert-triangle": AlertTriangle,
  "file-warning": FileWarning,
};

export function iconFor(name: string): LucideIcon {
  return ICON_MAP[name] || Monitor;
}
